#include "DemoApp.hpp"

#include <SDL3/SDL.h>

#include <cmath>   // std::cos, std::sin — cone cosines + the orbiting light
#include <memory>
#include <string>

#include "core/Engine.hpp"
#include "core/Log.hpp"
#include "renderer/GpuRenderer.hpp"
#include "renderer/Mesh.hpp"
#include "renderer/ModelLoader.hpp"
#include "renderer/Primitives.hpp"
#include "scene/Material.hpp"
#include "scene/Node.hpp"

namespace koi {

namespace {
// The colour the screen is cleared to for pixels the scene doesn't cover. A calm
// dark teal — distinctive enough that you can tell the GPU clear actually ran.
constexpr SDL_FColor kClearColor = {0.04f, 0.10f, 0.12f, 1.0f};
}  // namespace

// Out-of-line so the unique_ptr<Node> member sees the complete Node type (from
// scene/Node.hpp, included above) where it is constructed/destroyed.
DemoApp::DemoApp()  = default;
DemoApp::~DemoApp() = default;

bool DemoApp::onStart(Engine& engine) {
    // Build the world through the engine's renderer — the same surface any client
    // app would use. Then place the lights, and pose the scene (world transforms)
    // so a KOI_CAPTURE taken right after onStart renders the deterministic t=0 frame.
    if (!buildScene(engine.renderer())) {
        return false;
    }
    setupLights();
    sceneRoot_->updateWorldTransforms();

    KOI_INFO("Controls: WASD move, E/Q up/down, mouse look, Esc to quit.");
    KOI_INFO("Post-processing: 1=tone-map 2=bloom 3=FXAA 4=vignette, [ / ] exposure.");
    KOI_INFO("Lights: 5=point lights 6=spot 7=sun. Environment: 8=skybox 9=IBL.");
    return true;
}

bool DemoApp::buildScene(GpuRenderer& renderer) {
    // Two shared meshes, uploaded to the GPU once and reused by every node that
    // wants them. The cube is the RGB color cube from earlier steps; the plane is
    // a flat ground. shared_ptr lets many nodes point at the same geometry.
    std::shared_ptr<Mesh> cube  = makeCubeMesh(renderer);
    std::shared_ptr<Mesh> plane = makePlaneMesh(renderer);
    if (!cube || !plane) {
        KOI_ERROR("buildScene: failed to create one or more meshes.");
        return false;
    }

    // Albedo textures, resolved relative to the executable (same convention as the
    // shaders). They become the base-colour images of the materials below.
    const std::string base = SDL_GetBasePath() ? SDL_GetBasePath() : "";
    auto checkerTex = renderer.loadTexture((base + "assets/uv_grid.bmp").c_str());
    auto dotsTex    = renderer.loadTexture((base + "assets/dots.bmp").c_str());
    if (!checkerTex || !dotsTex) {
        KOI_ERROR("buildScene: failed to load one or more textures.");
        return false;
    }

    // Step 13: the "tiled panel" map set (generated by tools/gen_textures.py) — a
    // normal map (beveled tile grooves), a packed metallic-roughness map (grooves
    // rougher; tiles alternate metal/dielectric), and an AO map (dark grooves). We
    // layer these over the existing albedo images to drive the surface PER PIXEL.
    auto tileNormal = renderer.loadTexture((base + "assets/tiles_normal.bmp").c_str());
    auto tileMr     = renderer.loadTexture((base + "assets/tiles_mr.bmp").c_str());
    auto tileAo     = renderer.loadTexture((base + "assets/tiles_ao.bmp").c_str());
    auto tileAlbedo = renderer.loadTexture((base + "assets/tiles_albedo.bmp").c_str());
    if (!tileNormal || !tileMr || !tileAo || !tileAlbedo) {
        KOI_ERROR("buildScene: failed to load one or more texture maps.");
        return false;
    }

    // Step 14: the environment SKYBOX. Six procedural day-sky faces (generated by
    // tools/gen_skybox.py) are uploaded into one cube texture the renderer owns and
    // draws behind the scene. Order is SDL's cube layer order: +X,-X,+Y,-Y,+Z,-Z.
    // The sky is optional — if it fails to load we log and carry on (the scene still
    // renders against the flat clear colour).
    if (!renderer.loadCubemap({base + "assets/sky_px.bmp", base + "assets/sky_nx.bmp",
                               base + "assets/sky_py.bmp", base + "assets/sky_ny.bmp",
                               base + "assets/sky_pz.bmp", base + "assets/sky_nz.bmp"})) {
        KOI_WARN("buildScene: skybox cubemap failed to load — continuing without a sky.");
    }

    // Materials now vary appearance PER OBJECT and, where maps are attached, PER PIXEL.
    // Designated initializers keep the six fields readable (and silence
    // -Wmissing-field-initializers). A material with no maps falls back to the neutral
    // 1x1 textures in the renderer, rendering exactly as it did in Step 12:
    //   * floorMat — the showcase for RELIEF: the tile normal map gives the big flat
    //                plane real bumps under the raking sun, the AO map darkens the
    //                grooves, and the MR map varies roughness per pixel. Kept a
    //                DIELECTRIC (metallic factor 0) so the large surface isn't a dark
    //                metal (metals need IBL to look right — a later step).
    //   * hubMat   — the showcase for PER-PIXEL METALLIC + RELIEF: the full map set
    //                over a PLAIN tile albedo (so nothing competes with the effects),
    //                metallic factor 1, so the MR map's metal/dielectric checkerboard
    //                and the normal map's beveled tiles both show on the cube's faces.
    //   * cubeMat  — map-less (the fallback path): a plain mid-roughness dielectric,
    //                proving map-less materials are unchanged from Step 12.
    auto floorMat = std::make_shared<Material>(Material{
        .albedo = checkerTex, .metallic = 0.0f, .roughness = 1.0f,
        .metalRough = tileMr, .normalMap = tileNormal, .ao = tileAo});
    auto cubeMat  = std::make_shared<Material>(Material{
        .albedo = dotsTex, .metallic = 0.0f, .roughness = 0.55f});
    auto hubMat   = std::make_shared<Material>(Material{
        .albedo = tileAlbedo, .metallic = 1.0f, .roughness = 1.0f,
        .metalRough = tileMr, .normalMap = tileNormal, .ao = tileAo});

    // Step 9: load two MODELS from files. sphere.glb exercises the cgltf loader; torus.obj
    // the tinyobjloader one. We take only their geometry (.mesh) and give them our OWN
    // showcase materials below — unlike the Damaged Helmet further down, which keeps the
    // material imported from its file (Step 16).
    LoadedModel sphereModel = loadModel(renderer, (base + "assets/sphere.glb").c_str());
    LoadedModel torusModel  = loadModel(renderer, (base + "assets/torus.obj").c_str());
    std::shared_ptr<Mesh> sphere = sphereModel.mesh;
    std::shared_ptr<Mesh> torus  = torusModel.mesh;
    if (!sphere || !torus) {
        KOI_ERROR("buildScene: failed to load one or more models.");
        return false;
    }
    // The loaded models flank the cubes and headline the two material extremes:
    //   * sphereMat — a smooth METAL (the checker as its reflected tint): the Step 15
    //                 SHOWCASE. Before IBL a metal was near-black away from the highlight;
    //                 now it mirrors the sky. Roughness is low (0.08) so that reflection is
    //                 crisp — toggle IBL with '9' to watch it go dark again.
    //   * torusMat  — a glossy DIELECTRIC: a tight white specular over a matte body.
    auto sphereMat = std::make_shared<Material>(Material{
        .albedo = checkerTex, .metallic = 1.0f, .roughness = 0.08f});
    auto torusMat  = std::make_shared<Material>(Material{
        .albedo = dotsTex, .metallic = 0.0f, .roughness = 0.25f});

    // The root is a pure GROUP node (no mesh/material): a stable parent for the world.
    sceneRoot_ = std::make_unique<Node>();

    // A ground plane (checker, matte), dropped a couple of units below the cubes so
    // they sit above it. (Its own local transform places it; the mesh is centered.)
    auto ground = std::make_unique<Node>(plane, floorMat);
    ground->transform().position = {0.0f, -2.0f, 0.0f};
    sceneRoot_->addChild(std::move(ground));

    // The HUB: a cube at the origin that spins about Y (animated in onUpdate), with the
    // extra-shiny material. Every node below is placed in the hub's space, so they
    // orbit it as it turns — the whole point of a scene graph.
    hub_ = sceneRoot_->addChild(std::make_unique<Node>(cube, hubMat));

    // Two small satellites (glossy dots) at fixed offsets in the hub's space. As the
    // hub spins, they sweep around it, though their OWN transforms never change.
    auto satA = std::make_unique<Node>(cube, cubeMat);
    satA->transform().position = {2.5f, 0.0f, 0.0f};
    satA->transform().scale    = {0.5f, 0.5f, 0.5f};
    hub_->addChild(std::move(satA));

    auto satC = std::make_unique<Node>(cube, cubeMat);
    satC->transform().position = {0.0f, 0.0f, 2.5f};
    satC->transform().scale    = {0.5f, 0.5f, 0.5f};
    hub_->addChild(std::move(satC));

    // A third satellite that ALSO spins (the "spinner"/pivot), carrying a
    // grandchild "moon" offset from it. Result: the moon orbits the spinner
    // (because the spinner turns) WHILE the spinner orbits the hub (because the
    // hub turns) — two levels of inherited motion, with no special code.
    auto pivot = std::make_unique<Node>(cube, cubeMat);
    pivot->transform().position = {-2.5f, 0.0f, 0.0f};
    pivot->transform().scale    = {0.6f, 0.6f, 0.6f};
    spinner_ = hub_->addChild(std::move(pivot));

    auto moon = std::make_unique<Node>(cube, cubeMat);
    moon->transform().position = {2.0f, 0.0f, 0.0f};
    moon->transform().scale    = {0.6f, 0.6f, 0.6f};
    spinner_->addChild(std::move(moon));

    // The two loaded models, flanking the cube hierarchy and resting on the floor.
    auto sphereNode = std::make_unique<Node>(sphere, sphereMat);
    sphereNode->transform().position = {-3.8f, -0.8f, 0.0f};
    sphereNode->transform().scale    = {1.2f, 1.2f, 1.2f};
    sceneRoot_->addChild(std::move(sphereNode));

    auto torusNode = std::make_unique<Node>(torus, torusMat);
    torusNode->transform().position      = {3.8f, -0.3f, 0.0f};
    torusNode->transform().scale         = {1.2f, 1.2f, 1.2f};
    torusNode->transform().rotation = Quat::fromEuler({radians(90.0f), 0.0f, 0.0f});  // stand the donut up
    sceneRoot_->addChild(std::move(torusNode));

    // Step 16: the HERO — the Khronos "Damaged Helmet", a real production glTF PBR asset
    // (downloaded at configure time; see CMakeLists.txt). Loading it exercises the glTF
    // material import end-to-end: its base-colour, metallic-roughness, normal, AO and
    // EMISSIVE maps all come straight out of the .glb, decoded via stb_image. Unlike the
    // sphere/torus above we keep the FILE's material (helmet.material), not one we author.
    // The asset is optional — if it didn't download we log and carry on.
    //
    // We import raw primitive geometry and ignore glTF NODE transforms (a documented
    // deferral), and this model is authored Z-up, so we rotate it upright ourselves and
    // give it a 3/4 turn so the lit visor + emissive vents face the camera.
    LoadedModel helmet = loadModel(renderer, (base + "assets/DamagedHelmet.glb").c_str());
    if (helmet.mesh && helmet.material) {
        auto helmetNode = std::make_unique<Node>(helmet.mesh, helmet.material);
        helmetNode->transform().position      = {0.0f, 0.4f, 4.2f};
        helmetNode->transform().scale         = {1.6f, 1.6f, 1.6f};
        // Z-up asset → stand upright (~72° about X, a touch under 90° so the visor tilts
        // toward the elevated camera) + a 3/4 turn so the glowing eyes read as the hero.
        helmetNode->transform().rotation = Quat::fromEuler({radians(72.0f), radians(-22.0f), 0.0f});
        sceneRoot_->addChild(std::move(helmetNode));
        KOI_INFO("Scene built: ground + cube hierarchy + 3 loaded models "
                 "(sphere.glb, torus.obj, DamagedHelmet.glb w/ imported PBR material).");
    } else {
        KOI_WARN("buildScene: DamagedHelmet.glb not loaded — continuing without it "
                 "(re-run CMake configure with network access to fetch the asset).");
        KOI_INFO("Scene built: ground + cube hierarchy + 2 loaded models (sphere.glb, torus.obj).");
    }
    return true;
}

void DemoApp::setupLights() {
    lights_.clear();

    // Light 0 — the SUN: a directional light (parallel rays, no distance falloff).
    // This is the ONLY shadow caster — by convention it lives at index 0, which the
    // renderer/shader rely on. Step 12 note: the PBR shading divides diffuse by π and
    // conserves energy, so intensities are larger than the Blinn-Phong era to land at
    // a comparable brightness.
    Light sun;
    sun.type      = LightType::Directional;
    sun.direction = {-0.4f, -1.0f, -0.3f};  // the direction the rays TRAVEL
    sun.color     = {1.0f, 1.0f, 1.0f};
    sun.intensity = 3.0f;
    lights_.push_back(sun);

    // Light 1 — a warm POINT light off to the right, pooling orange light on the
    // torus and the floor. A point light falls off with distance (see `range`), so
    // nearby surfaces glow while far ones barely register — unlike the sun.
    Light warm;
    warm.type      = LightType::Point;
    warm.position  = {3.6f, 1.2f, 2.2f};
    warm.color     = {1.0f, 0.45f, 0.15f};
    warm.intensity = 24.0f;
    warm.range     = 9.0f;
    lights_.push_back(warm);

    // Light 2 — a cool blue POINT light that ORBITS the scene (animated in onUpdate),
    // so its colored pool sweeps across every surface and the multi-light effect is
    // unmistakable in motion. Its starting position also reads in the t=0 capture.
    Light cool;
    cool.type      = LightType::Point;
    cool.position  = {-3.6f, 1.3f, 2.2f};
    cool.color     = {0.25f, 0.5f, 1.0f};
    cool.intensity = 24.0f;
    cool.range     = 9.0f;
    lights_.push_back(cool);

    // Light 3 — a SPOT light overhead, aimed down at the hub, casting a soft-edged
    // cone of greenish light on the cubes and a ring on the floor. Cutoffs are
    // stored as COSINES of the cone half-angles; because cos DECREASES with angle,
    // the inner (full-bright) cutoff cosine is LARGER than the outer (zero) one.
    Light spot;
    spot.type           = LightType::Spot;
    spot.position       = {0.0f, 4.5f, 1.0f};
    spot.direction      = {0.0f, -1.0f, -0.15f};  // mostly straight down
    spot.color          = {0.7f, 1.0f, 0.7f};
    spot.intensity      = 40.0f;
    spot.range          = 16.0f;
    spot.innerCutoffCos = std::cos(radians(14.0f));
    spot.outerCutoffCos = std::cos(radians(22.0f));
    lights_.push_back(spot);

    KOI_INFO("Lights: 1 directional sun (shadow caster) + 2 point + 1 spot.");
}

void DemoApp::onUpdate(Engine& /*engine*/, float dt) {
    // Continuous input: read the CURRENT keyboard state (not key-down events) so held
    // keys produce smooth, repeat-rate-independent movement.
    camera_.processKeyboard(SDL_GetKeyboardState(nullptr), dt);

    // Animate the scene: spin the hub (its satellites orbit with it) and the inner
    // pivot (its moon orbits it). A quaternion has no per-axis angle to bump, so we
    // keep the running Y angle ourselves (radians, scaled by dt for frame-rate
    // independence) and rebuild the rotation from axis-angle each frame. Rebuilding
    // fresh also avoids the slow drift off unit length that accumulating quaternion
    // multiplies would cause.
    hubSpin_     += 0.6f * dt;
    spinnerSpin_ += 1.5f * dt;
    hub_->transform().rotation     = Quat::fromAxisAngle({0.0f, 1.0f, 0.0f}, hubSpin_);
    spinner_->transform().rotation = Quat::fromAxisAngle({0.0f, 1.0f, 0.0f}, spinnerSpin_);

    // Orbit the cool point light (index 2) around the scene so its colored pool
    // sweeps across the surfaces — the clearest way to SEE a moving light.
    lightOrbit_ += 0.8f * dt;
    if (lights_.size() > 2) {
        lights_[2].position = {3.6f * std::cos(lightOrbit_), 1.3f,
                               3.6f * std::sin(lightOrbit_)};
    }

    // Propagate transforms down the tree (parent → child → grandchild) so every
    // node's cached world matrix is current before the engine draws this frame.
    sceneRoot_->updateWorldTransforms();
}

void DemoApp::onEvent(Engine& engine, const SDL_Event& event) {
    switch (event.type) {
        case SDL_EVENT_KEY_DOWN:
            // In SDL3, event.key.key holds the virtual keycode. ESC quits; the number
            // keys toggle each post-processing effect / light group and the brackets
            // nudge exposure, so the reader can watch what every effect does.
            switch (event.key.key) {
                case SDLK_ESCAPE:
                    KOI_INFO("Escape pressed — shutting down.");
                    engine.requestQuit();
                    break;
                case SDLK_1:
                    post_.tonemap = !post_.tonemap;
                    KOI_INFO("Tone-mapping: %s", post_.tonemap ? "on" : "off");
                    break;
                case SDLK_2:
                    post_.bloom = !post_.bloom;
                    KOI_INFO("Bloom: %s", post_.bloom ? "on" : "off");
                    break;
                case SDLK_3:
                    post_.fxaa = !post_.fxaa;
                    KOI_INFO("FXAA: %s", post_.fxaa ? "on" : "off");
                    break;
                case SDLK_4:
                    post_.vignette = !post_.vignette;
                    KOI_INFO("Vignette: %s", post_.vignette ? "on" : "off");
                    break;
                case SDLK_LEFTBRACKET:  // '[' — darker
                    post_.exposure = SDL_max(0.1f, post_.exposure / 1.25f);
                    KOI_INFO("Exposure: %.2f", post_.exposure);
                    break;
                case SDLK_RIGHTBRACKET:  // ']' — brighter
                    post_.exposure = SDL_min(8.0f, post_.exposure * 1.25f);
                    KOI_INFO("Exposure: %.2f", post_.exposure);
                    break;
                case SDLK_5: {
                    // Toggle the two colored POINT lights together (indices 1-2).
                    const bool on = (lights_.size() > 1) ? !lights_[1].enabled : false;
                    if (lights_.size() > 1) {
                        lights_[1].enabled = on;
                    }
                    if (lights_.size() > 2) {
                        lights_[2].enabled = on;
                    }
                    KOI_INFO("Point lights: %s", on ? "on" : "off");
                    break;
                }
                case SDLK_6:
                    // Toggle the SPOT light (index 3).
                    if (lights_.size() > 3) {
                        lights_[3].enabled = !lights_[3].enabled;
                        KOI_INFO("Spot light: %s", lights_[3].enabled ? "on" : "off");
                    }
                    break;
                case SDLK_7:
                    // Toggle the directional SUN (index 0). With it off, the point/spot
                    // lights (which cast no shadow) light the scene alone.
                    if (!lights_.empty()) {
                        lights_[0].enabled = !lights_[0].enabled;
                        KOI_INFO("Sun: %s", lights_[0].enabled ? "on" : "off");
                    }
                    break;
                case SDLK_8: {
                    // Step 14: toggle the SKYBOX so its effect is easy to see (with it
                    // off, the background falls back to the flat clear colour).
                    const bool on = !engine.renderer().skyboxEnabled();
                    engine.renderer().setSkyboxEnabled(on);
                    KOI_INFO("Skybox: %s", on ? "on" : "off");
                    break;
                }
                case SDLK_9: {
                    // Step 15: toggle IMAGE-BASED LIGHTING. With it off, the ambient
                    // term falls back to the flat constant fill (the Step 12 look), so
                    // the metal sphere goes dark — a clean A/B for what the environment
                    // actually contributes.
                    const bool on = !engine.renderer().iblEnabled();
                    engine.renderer().setIblEnabled(on);
                    KOI_INFO("Image-based lighting: %s", on ? "on" : "off");
                    break;
                }
                default:
                    break;
            }
            break;

        case SDL_EVENT_MOUSE_MOTION:
            // Relative mouse mode reports motion as deltas (xrel/yrel). We feed them
            // straight into the camera as a yaw/pitch change — FPS look.
            camera_.addMouseLook(event.motion.xrel, event.motion.yrel);
            break;

        case SDL_EVENT_WINDOW_RESIZED:
            // The swapchain (and the depth texture) auto-resize, and the renderer
            // recomputes the aspect ratio from the swapchain size each frame, so
            // there's nothing to do here but log it.
            KOI_DEBUG("Window resized to %dx%d", event.window.data1, event.window.data2);
            break;

        default:
            break;
    }
}

FrameView DemoApp::frameView() const {
    // Hand the engine a read-only snapshot of what to draw: our clear colour, the
    // camera's view + eye, the scene root, the light list, and the post settings.
    // `lights_` outlives this call (it's a member), so the span stays valid.
    return FrameView{
        .clearColor = kClearColor,
        .view       = camera_.viewMatrix(),
        .root       = sceneRoot_.get(),
        .cameraPos  = camera_.position(),
        .lights     = lights_,
        .post       = post_,
    };
}

void DemoApp::onShutdown() {
    // Release the scene BEFORE the engine destroys the GPU device: the meshes' buffers
    // and the materials' textures are freed through that device. The engine calls this
    // from run() while the renderer is still alive, so this ordering is guaranteed.
    sceneRoot_.reset();
    hub_     = nullptr;  // dangling now that the tree is gone
    spinner_ = nullptr;
}

}  // namespace koi
